# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish NuGet Packages

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Trigger on tags like v1.0.0, v1.2.3-beta

jobs:
  publish:
    name: Build, Pack & Publish
    runs-on: ubuntu-latest
    permissions:
        contents: read # for checking out repo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Extract version from Tag
      id: get_version
      run: echo "package_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Publish
      run: ./scripts/publish.sh ${{ steps.get_version.outputs.package_version }}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
